version: '3.8'

services:
  app:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    image: laravel-docker-app
    container_name: laravel-app
    working_dir: /var/www
    ports:
      - "9000:9000"
    expose:
      - 9000
    volumes:
      - .:/var/www
      - storage-data:/var/www/storage
    depends_on:
      - mysql
      - npm

  web:
    image: nginx:alpine
    container_name: laravel-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  npm:
    image: node:18-alpine
    container_name: laravel-npm
    working_dir: /var/www
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  storage-data:
